//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.ApplicationAttachments = new HashSet<ApplicationAttachment>();
            this.ApplicationExchangeOptions = new HashSet<ApplicationExchangeOption>();
            this.ApplicationOptionValues = new HashSet<ApplicationOptionValue>();
            this.Interviews = new HashSet<Interview>();
            this.InterviewComments = new HashSet<InterviewComment>();
            this.NominationApplications = new HashSet<NominationApplication>();
            this.ApplicationComments = new HashSet<ApplicationComment>();
        }
    
        public int id { get; set; }
        public string student_id { get; set; }
        public int program_id { get; set; }
        public int status_id { get; set; }
        public bool shortlisted { get; set; }
        public bool nominated { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public Nullable<System.DateTime> submitted { get; set; }
        public Nullable<int> appointment_id { get; set; }
    
        public virtual ApplicationStatus ApplicationStatus { get; set; }
        public virtual Program Program { get; set; }
        public virtual StudentProfile StudentProfile { get; set; }
        public virtual ICollection<ApplicationAttachment> ApplicationAttachments { get; set; }
        public virtual ICollection<ApplicationExchangeOption> ApplicationExchangeOptions { get; set; }
        public virtual ICollection<ApplicationOptionValue> ApplicationOptionValues { get; set; }
        public virtual ICollection<Interview> Interviews { get; set; }
        public virtual ICollection<InterviewComment> InterviewComments { get; set; }
        public virtual ICollection<NominationApplication> NominationApplications { get; set; }
        public virtual ICollection<ApplicationComment> ApplicationComments { get; set; }
    }
}
