//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationExchangeOption
    {
        public int id { get; set; }
        public int application_id { get; set; }
        public Nullable<int> exchange_option_id { get; set; }
        public int priority { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual ExchangeOption ExchangeOption { get; set; }
    }
}
