//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public Appointment()
        {
            this.AppointmentConcerns = new HashSet<AppointmentConcern>();
        }
    
        public int id { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public int host_id { get; set; }
        public int status_id { get; set; }
        public int venue_id { get; set; }
        public string student_id { get; set; }
        public string remarks { get; set; }
    
        public virtual AppointmentHost AppointmentHost { get; set; }
        public virtual AppointmentStatus AppointmentStatus { get; set; }
        public virtual AppointmentVenue AppointmentVenue { get; set; }
        public virtual StudentProfile StudentProfile { get; set; }
        public virtual ICollection<AppointmentConcern> AppointmentConcerns { get; set; }
    }
}
