//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterviewStatus
    {
        public InterviewStatus()
        {
            this.Interviews = new HashSet<Interview>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool locked { get; set; }
        public bool display_to_student { get; set; }
    
        public virtual ICollection<Interview> Interviews { get; set; }
    }
}
