//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NominationApplication
    {
        public int id { get; set; }
        public int nomination_level_id { get; set; }
        public int nominator_id { get; set; }
        public int application_id { get; set; }
        public System.DateTime nominated_date { get; set; }
        public string remarks { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual NominationLevel NominationLevel { get; set; }
        public virtual Nominator Nominator { get; set; }
    }
}
