//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NominationList
    {
        public NominationList()
        {
            this.NominationApplications = new HashSet<NominationApplication>();
        }
    
        public int id { get; set; }
        public int nomination_id { get; set; }
        public int nominator_userid { get; set; }
        public int nomination_level { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public int quota { get; set; }
        public string remarks { get; set; }
        public string name { get; set; }
    
        public virtual Nomination Nomination { get; set; }
        public virtual SystemUser UserProfile { get; set; }
        public virtual ICollection<NominationApplication> NominationApplications { get; set; }
    }
}
