//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NominationApplication
    {
        public int id { get; set; }
        public int nomination_id { get; set; }
        public int nomination_list_id { get; set; }
        public int application_id { get; set; }
        public bool nominated { get; set; }
        public Nullable<System.DateTime> nominate_date { get; set; }
        public string remarks { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Nomination Nomination { get; set; }
        public virtual NominationList NominationList { get; set; }
    }
}
