//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nominator
    {
        public Nominator()
        {
            this.NominationApplications = new HashSet<NominationApplication>();
        }
    
        public int id { get; set; }
        public int nomination_level_id { get; set; }
        public string nominator_username { get; set; }
        public int quota { get; set; }
    
        public virtual ICollection<NominationApplication> NominationApplications { get; set; }
        public virtual NominationLevel NominationLevel { get; set; }
    }
}
