//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public Notification()
        {
            this.NotificationRecipients = new HashSet<NotificationRecipient>();
        }
    
        public int id { get; set; }
        public System.DateTime send_time { get; set; }
        public string sender { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public int status_id { get; set; }
        public int type_id { get; set; }
        public string created_by { get; set; }
        public System.DateTime created { get; set; }
        public string modified_by { get; set; }
        public System.DateTime modified { get; set; }
        public Nullable<int> template_id { get; set; }
        public Nullable<int> program_id { get; set; }
        public Nullable<int> application_id { get; set; }
        public Nullable<int> interview_id { get; set; }
        public Nullable<int> appointment_id { get; set; }
        public Nullable<int> nomination_id { get; set; }
    
        public virtual NotificationStatus NotificationStatus { get; set; }
        public virtual NotificationTemplate NotificationTemplate { get; set; }
        public virtual NotificationType NotificationType { get; set; }
        public virtual ICollection<NotificationRecipient> NotificationRecipients { get; set; }
    }
}
