//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public Program()
        {
            this.Applications = new HashSet<Application>();
            this.AppointmentConcerns = new HashSet<AppointmentConcern>();
            this.Interviews = new HashSet<Interview>();
            this.Nominations = new HashSet<Nomination>();
            this.ProgramApplicationAttachments = new HashSet<ProgramApplicationAttachment>();
            this.ProgramAttachments = new HashSet<ProgramAttachment>();
            this.ProgramOptionValues = new HashSet<ProgramOptionValue>();
        }
    
        public int id { get; set; }
        public int type_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string start_time { get; set; }
        public string end_time { get; set; }
        public int status_id { get; set; }
        public string host_name { get; set; }
        public string website { get; set; }
        public string job_position { get; set; }
        public string eligible_academic_career { get; set; }
        public string eligible_academic_organization { get; set; }
        public string eligible_academic_plan { get; set; }
        public string eligible_academic_level { get; set; }
        public string eligible_program_status { get; set; }
        public string eligibility { get; set; }
        public string note_exchange { get; set; }
        public bool require_interview { get; set; }
        public bool require_nomination { get; set; }
        public bool require_appointment { get; set; }
        public bool require_exchange_option { get; set; }
        public string special_criteria { get; set; }
        public System.DateTime application_start_time { get; set; }
        public System.DateTime application_end_time { get; set; }
        public Nullable<System.DateTime> deadline_reminder_date { get; set; }
        public Nullable<int> vacancies { get; set; }
        public string apply_action { get; set; }
        public string apply_link { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public string published_by { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public Nullable<System.DateTime> published { get; set; }
        public string enquiry { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<AppointmentConcern> AppointmentConcerns { get; set; }
        public virtual ICollection<Interview> Interviews { get; set; }
        public virtual ICollection<Nomination> Nominations { get; set; }
        public virtual ProgramStatus ProgramStatus { get; set; }
        public virtual ProgramType ProgramType { get; set; }
        public virtual ICollection<ProgramApplicationAttachment> ProgramApplicationAttachments { get; set; }
        public virtual ICollection<ProgramAttachment> ProgramAttachments { get; set; }
        public virtual ICollection<ProgramOptionValue> ProgramOptionValues { get; set; }
    }
}
