//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramType
    {
        public ProgramType()
        {
            this.Programs = new HashSet<Program>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string shortname { get; set; }
        public string display_date { get; set; }
        public string image_filename { get; set; }
        public string image_filepath { get; set; }
        public bool display_on_menu { get; set; }
        public bool display_on_showcase { get; set; }
        public int priority { get; set; }
    
        public virtual ICollection<Program> Programs { get; set; }
    }
}
