//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramApplicationAttachment
    {
        public ProgramApplicationAttachment()
        {
            this.ApplicationAttachments = new HashSet<ApplicationAttachment>();
        }
    
        public int id { get; set; }
        public int program_id { get; set; }
        public string name { get; set; }
        public bool required { get; set; }
        public string mime_type_allowed { get; set; }
    
        public virtual ICollection<ApplicationAttachment> ApplicationAttachments { get; set; }
        public virtual Program Program { get; set; }
    }
}
