//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolOfScienceEntities : DbContext
    {
        public SchoolOfScienceEntities()
            : base("name=SchoolOfScienceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<Application> Applications { get; set; }
        public DbSet<ApplicationAttachment> ApplicationAttachments { get; set; }
        public DbSet<ApplicationExchangeOption> ApplicationExchangeOptions { get; set; }
        public DbSet<ApplicationOptionValue> ApplicationOptionValues { get; set; }
        public DbSet<ApplicationStatus> ApplicationStatus { get; set; }
        public DbSet<Appointment> Appointments { get; set; }
        public DbSet<AppointmentConcern> AppointmentConcerns { get; set; }
        public DbSet<AppointmentHost> AppointmentHosts { get; set; }
        public DbSet<AppointmentStatus> AppointmentStatus { get; set; }
        public DbSet<ExchangeOption> ExchangeOptions { get; set; }
        public DbSet<Interview> Interviews { get; set; }
        public DbSet<InterviewStatus> InterviewStatus { get; set; }
        public DbSet<InterviewVenue> InterviewVenues { get; set; }
        public DbSet<Nomination> Nominations { get; set; }
        public DbSet<NominationStatus> NominationStatus { get; set; }
        public DbSet<Notification> Notifications { get; set; }
        public DbSet<NotificationRecipient> NotificationRecipients { get; set; }
        public DbSet<NotificationStatus> NotificationStatus { get; set; }
        public DbSet<NotificationTemplate> NotificationTemplates { get; set; }
        public DbSet<NotificationType> NotificationTypes { get; set; }
        public DbSet<Program> Programs { get; set; }
        public DbSet<ProgramApplicationAttachment> ProgramApplicationAttachments { get; set; }
        public DbSet<ProgramAttachment> ProgramAttachments { get; set; }
        public DbSet<ProgramOptionValue> ProgramOptionValues { get; set; }
        public DbSet<ProgramStatus> ProgramStatus { get; set; }
        public DbSet<ProgramType> ProgramTypes { get; set; }
        public DbSet<StudentCourseHistory> StudentCourseHistories { get; set; }
        public DbSet<StudentExperience> StudentExperiences { get; set; }
        public DbSet<StudentExperienceType> StudentExperienceTypes { get; set; }
        public DbSet<StudentParticular> StudentParticulars { get; set; }
        public DbSet<StudentParticularType> StudentParticularTypes { get; set; }
        public DbSet<StudentProfile> StudentProfiles { get; set; }
        public DbSet<StudentPublicExam> StudentPublicExams { get; set; }
        public DbSet<StudentTerm> StudentTerms { get; set; }
        public DbSet<Timeslot> Timeslots { get; set; }
        public DbSet<TimeslotConfig> TimeslotConfigs { get; set; }
        public DbSet<TimeslotConfigSession> TimeslotConfigSessions { get; set; }
        public DbSet<SystemUser> SystemUsers { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<SystemRole> SystemRoles { get; set; }
        public DbSet<StudentAcademicPlan> StudentAcademicPlans { get; set; }
        public DbSet<StudentQualification> StudentQualifications { get; set; }
        public DbSet<StudentAdvisingRemark> StudentAdvisingRemarks { get; set; }
        public DbSet<StudentAdvisor> StudentAdvisors { get; set; }
        public DbSet<StudentAdmission> StudentAdmissions { get; set; }
        public DbSet<StudentMajorChoice> StudentMajorChoices { get; set; }
        public DbSet<StudentActivity> StudentActivities { get; set; }
        public DbSet<InterviewComment> InterviewComments { get; set; }
        public DbSet<NominationApplication> NominationApplications { get; set; }
        public DbSet<NominationLevel> NominationLevels { get; set; }
        public DbSet<Nominator> Nominators { get; set; }
    }
}
