//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentProfile
    {
        public StudentProfile()
        {
            this.Applications = new HashSet<Application>();
            this.Appointments = new HashSet<Appointment>();
            this.NotificationRecipients = new HashSet<NotificationRecipient>();
            this.StudentCourseHistories = new HashSet<StudentCourseHistory>();
            this.StudentExperiences = new HashSet<StudentExperience>();
            this.StudentParticulars = new HashSet<StudentParticular>();
            this.StudentPublicExams = new HashSet<StudentPublicExam>();
            this.StudentTerms = new HashSet<StudentTerm>();
            this.StudentQualifications = new HashSet<StudentQualification>();
            this.StudentAdvisingRemarks = new HashSet<StudentAdvisingRemark>();
            this.StudentAdvisors = new HashSet<StudentAdvisor>();
            this.StudentMajorChoices = new HashSet<StudentMajorChoice>();
            this.StudentActivities = new HashSet<StudentActivity>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public string academic_group { get; set; }
        public string academic_organization { get; set; }
        public string academic_career { get; set; }
        public string academic_program { get; set; }
        public string academic_plan_primary { get; set; }
        public string academic_plan_description { get; set; }
        public string academic_load { get; set; }
        public string academic_level { get; set; }
        public string student_career_number { get; set; }
        public string study_form { get; set; }
        public string study_form_description { get; set; }
        public string program_status { get; set; }
        public string program_status_description { get; set; }
        public string study_agreement { get; set; }
        public string chinese_name { get; set; }
        public string hkid { get; set; }
        public string passport { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string gender { get; set; }
        public string citizenship { get; set; }
        public string citizenship_description { get; set; }
        public string residence_code { get; set; }
        public string residence_code_description { get; set; }
        public string native_place_code { get; set; }
        public string native_place_code_description { get; set; }
        public string local_or_nonlocal { get; set; }
        public string email { get; set; }
        public string dormitory_address1 { get; set; }
        public string dormitory_address2 { get; set; }
        public string mailing_address1 { get; set; }
        public string mailing_address2 { get; set; }
        public string mailing_address3 { get; set; }
        public string mailing_address4 { get; set; }
        public string mailing_postal_code { get; set; }
        public string mailing_area_code { get; set; }
        public string mailing_country { get; set; }
        public string home_address1 { get; set; }
        public string home_address2 { get; set; }
        public string home_address3 { get; set; }
        public string home_address4 { get; set; }
        public string home_postal_code { get; set; }
        public string home_area_code { get; set; }
        public string home_country { get; set; }
        public string home_phone_country_code { get; set; }
        public string home_phone_number { get; set; }
        public string contact_phone_country_code { get; set; }
        public string contact_phone_number { get; set; }
        public string mobile_phone_country_code { get; set; }
        public string mobile_phone_number { get; set; }
        public string barcode { get; set; }
        public string interests { get; set; }
        public string goals { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public string remarks { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<NotificationRecipient> NotificationRecipients { get; set; }
        public virtual ICollection<StudentCourseHistory> StudentCourseHistories { get; set; }
        public virtual ICollection<StudentExperience> StudentExperiences { get; set; }
        public virtual ICollection<StudentParticular> StudentParticulars { get; set; }
        public virtual ICollection<StudentPublicExam> StudentPublicExams { get; set; }
        public virtual ICollection<StudentTerm> StudentTerms { get; set; }
        public virtual StudentAcademicPlan StudentAcademicPlan { get; set; }
        public virtual ICollection<StudentQualification> StudentQualifications { get; set; }
        public virtual ICollection<StudentAdvisingRemark> StudentAdvisingRemarks { get; set; }
        public virtual ICollection<StudentAdvisor> StudentAdvisors { get; set; }
        public virtual StudentAdmission StudentAdmission { get; set; }
        public virtual ICollection<StudentMajorChoice> StudentMajorChoices { get; set; }
        public virtual ICollection<StudentActivity> StudentActivities { get; set; }
    }
}
