//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourseHistory
    {
        public int id { get; set; }
        public string student_id { get; set; }
        public string course_attempt_term { get; set; }
        public string course_attempt_description { get; set; }
        public string course_academic_group { get; set; }
        public string course_academic_organization { get; set; }
        public string course_id { get; set; }
        public string course_subject_area { get; set; }
        public string course_catalog_number { get; set; }
        public string course_title { get; set; }
        public string course_enroll_status { get; set; }
        public Nullable<int> units_taken { get; set; }
        public Nullable<int> units_earned { get; set; }
        public string course_grade { get; set; }
        public string include_for_gpa { get; set; }
        public string include_for_gga { get; set; }
    
        public virtual StudentProfile StudentProfile { get; set; }
    }
}
