//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAdvisingRemark
    {
        public int id { get; set; }
        public string student_id { get; set; }
        public string text { get; set; }
        public string filename { get; set; }
        public string filepath { get; set; }
        public bool @private { get; set; }
        public System.DateTime created { get; set; }
        public string created_by { get; set; }
        public System.DateTime modified { get; set; }
        public string modified_by { get; set; }
        public System.DateTime display_date { get; set; }
    
        public virtual StudentProfile StudentProfile { get; set; }
    }
}
