//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAdmission
    {
        public string student_id { get; set; }
        public string Student_Name { get; set; }
        public string Admit_Type { get; set; }
        public string Admit_Type_Description { get; set; }
        public string Basis_of_Admission { get; set; }
        public string Basis_of_Admission_description { get; set; }
        public string Cohort_Term { get; set; }
        public string Cohort_Term_Description { get; set; }
        public string Admit_Term { get; set; }
        public string Admit_Term_Description { get; set; }
        public string Admitted_Primary_Plan { get; set; }
        public string Admitted_Primary_Plan_Description { get; set; }
        public string Admitted_Academic_Load { get; set; }
        public string Admitted_Academic_Level { get; set; }
        public string Last_Attended_Secondary_School_Code { get; set; }
        public string Last_Attended_Secondary_School_Name { get; set; }
        public string Last_Attended_Institution_Code { get; set; }
        public string Last_Attended_Institution_Name { get; set; }
        public string Current_Academic_Group { get; set; }
        public string Current_Academic_Organization_Description { get; set; }
        public string Current_Academic_Career { get; set; }
        public string Current_Student_Career_Number { get; set; }
        public string Current_Academic_Program { get; set; }
        public string Current_Academic_Plan__Primary_ { get; set; }
        public string Current_Academic_Plan_Description { get; set; }
        public string Current_Major_Plan_2 { get; set; }
        public string Current_Major_Plan_3 { get; set; }
        public string Current_Major_Plan_4 { get; set; }
        public string Current_Minor_Plan_1 { get; set; }
        public string Current_Minor_Plan_2 { get; set; }
        public string Current_Minor_Plan_3 { get; set; }
        public string Current_Minor_Plan_4 { get; set; }
        public string Current_Prep_EAS_Plan { get; set; }
        public string Current_Academic_Load { get; set; }
        public string Current_Academic_Level { get; set; }
        public string Current_Form_of_Study { get; set; }
        public string Current_Form_of_Study_Descritpion { get; set; }
        public string Current_Program_Status { get; set; }
        public string Current_Program_Status_Description { get; set; }
        public string Current_Study_Agreement { get; set; }
        public string As_of_Term { get; set; }
        public string As_of_Term_Description { get; set; }
        public string Term_GPA { get; set; }
        public string Cumulative_GPA { get; set; }
        public string Cumulative_Credits_Earned_in_UST { get; set; }
        public string Credits_Earned_Elsewhere { get; set; }
        public string Potential_Graduate_Indicator { get; set; }
        public string Degree_Check_out_status { get; set; }
        public string Degree_Check_out_status_Description { get; set; }
        public string Expected_Graduation_Term { get; set; }
        public string Expected_Graduation_Term_Description { get; set; }
        public string Completion_Term { get; set; }
        public string Completion_Term_Description { get; set; }
        public string Confer_Date___01 { get; set; }
        public string Degree_Code___01 { get; set; }
        public string Degree_Title___01 { get; set; }
        public string Degree_Honor_Code___01 { get; set; }
        public string Degree_Honor_Description___01 { get; set; }
        public string Confer_Date___02 { get; set; }
        public string Degree_Code___02 { get; set; }
        public string Degree_Title___02 { get; set; }
        public string Degree_Honor_Code___02 { get; set; }
        public string Degree_Honor_Description___02 { get; set; }
        public string GGA_Grade_Points__Primary_Degree_Plan_ { get; set; }
        public string GGA_Grade_Points__2nd_Degree_Plan_ { get; set; }
        public string SGA__12pts_ { get; set; }
        public string CGA__12pts_ { get; set; }
        public string Overall_GGA__12pts_ { get; set; }
        public string C12_points_scale { get; set; }
    
        public virtual StudentProfile StudentProfile { get; set; }
    }
}
