//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAdvisor
    {
        public int id { get; set; }
        public string student_id { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public string advisor_role { get; set; }
        public string advisor_role_description { get; set; }
        public Nullable<int> advisor_number { get; set; }
        public string advisor_email { get; set; }
        public string advisor_name { get; set; }
    
        public virtual StudentProfile StudentProfile { get; set; }
    }
}
