//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTerm
    {
        public int id { get; set; }
        public string student_id { get; set; }
        public string term { get; set; }
        public string term_description { get; set; }
        public string term_academic_plan { get; set; }
        public string term_academic_plan_description { get; set; }
        public decimal term_gpa { get; set; }
        public decimal cumulative_gpa { get; set; }
    
        public virtual StudentProfile StudentProfile { get; set; }
    }
}
