//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPublicExam
    {
        public int id { get; set; }
        public string student_id { get; set; }
        public string test_description { get; set; }
        public string test_year { get; set; }
        public string test_component { get; set; }
        public string letter_score { get; set; }
        public string test_score { get; set; }
    
        public virtual StudentProfile StudentProfile { get; set; }
    }
}
