//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAcademicPlan
    {
        public int id { get; set; }
        public string student_id { get; set; }
        public string major_plan1 { get; set; }
        public string major_plan2 { get; set; }
        public string major_plan3 { get; set; }
        public string major_plan4 { get; set; }
        public string minor_plan1 { get; set; }
        public string minor_plan2 { get; set; }
        public string minor_plan3 { get; set; }
        public string minor_plan4 { get; set; }
    
        public virtual StudentProfile StudentProfile { get; set; }
    }
}
