//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentExperience
    {
        public int id { get; set; }
        public int type_id { get; set; }
        public string student_id { get; set; }
        public int start_month { get; set; }
        public int start_year { get; set; }
        public int end_month { get; set; }
        public int end_year { get; set; }
        public string organization { get; set; }
        public string position { get; set; }
        public string duty_description { get; set; }
    
        public virtual StudentExperienceType StudentExperienceType { get; set; }
        public virtual StudentProfile StudentProfile { get; set; }
    }
}
