//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfScience.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeslotConfig
    {
        public TimeslotConfig()
        {
            this.Timeslots = new HashSet<Timeslot>();
            this.TimeslotConfigSessions = new HashSet<TimeslotConfigSession>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public bool monday { get; set; }
        public bool tuesday { get; set; }
        public bool wednesday { get; set; }
        public bool thursday { get; set; }
        public bool friday { get; set; }
        public bool saturday { get; set; }
        public bool sunday { get; set; }
        public bool holiday { get; set; }
    
        public virtual ICollection<Timeslot> Timeslots { get; set; }
        public virtual ICollection<TimeslotConfigSession> TimeslotConfigSessions { get; set; }
    }
}
